server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/takeout_system?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update # 避免重复创建唯一约束/外键导致启动报错
      # ddl-auto: create-drop
    show-sql: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
mybatis:
  mapper-locations: classpath*:xml/*.xml
  type-aliases-package: com.example.entity

# DeepSeek AI Configuration
deepseek:
  api:
    key: ${DEEPSEEK_API_KEY:sk-11944b7b61964dcebcb8a16001c2b020}
    url: ${DEEPSEEK_API_URL:https://api.deepseek.com}
  model: ${DEEPSEEK_MODEL:deepseek-chat}